---
abstract: 'Simple, Reusable Module Tests'
author:
  - 'Ingy döt Net <ingy@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Test::Common
name: Test-Common
no_index:
  directory:
    - inc
    - share
    - t
requires:
  App::Cmd: 0.311
  File::Copy: 2.14
  File::Share: 0.01
  IO::All: 0.41
  Mouse: 0.93
  MouseX::App::Cmd: 0.08
  Template::Toolkit::Simple: 0.13
  YAML::XS: 0.35
  perl: 5.8.3
resources:
  homepage: http://github.com/ingydotnet/test-common-pm/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/ingydotnet/test-common-pm.git
version: 0.07
